-- Runs automatically at the end of every `npm run db:reset`.
--
-- Deliberately empty of family_members rows, and that is the whole point of the file
-- existing: handle_new_auth_user() picks the admin with
--
--     not exists (select 1 from family_members)
--
-- so a seeded member would leave your real sign-in stranded as 'pending', waiting on an
-- admin who does not exist. The fake family is inserted afterwards by `npm run db:seed`
-- instead, anchored on the row your sign-in created.
--
-- docs/setup/local-development.md#resetting-and-seeding
