-- Runs automatically at the end of every `npm run db:reset`.
--
-- Deliberately empty, and that is the whole point of the file existing. Identity comes
-- from a Google account: `handle_new_auth_user()` writes the one `app_users` row when you
-- first sign in, and there is no way to fabricate that row here without fabricating the
-- sign-in it belongs to.
--
-- So the development fixture arrives afterwards, from `npm run db:seed`, which anchors on
-- the account your sign-in created and builds a group, three relatives and their wishes
-- around it.
--
-- docs/setup/local-development.md#resetting-and-seeding
