-- Family Wish List — live updates
--
-- There is nothing to run here. This file exists so that the next person to
-- reach for `postgres_changes` finds the reason not to, next to the schema.
--
-- Live updates broadcast a content-free ping on a public Supabase Realtime
-- channel. Broadcast needs no database objects and no policies, so 0001_init.sql
-- stands unchanged: RLS on every table, zero policies, the anon key opens
-- nothing.
--
-- DO NOT add an RLS policy to `wishes` to make postgres_changes work, and DO NOT
-- put anything in the broadcast payload. Both would hand every list owner their
-- own claimed_by values, which is the one thing this app exists to prevent.
--
-- Why, in full, including the private-channel option that was considered and
-- rejected: docs/content/live-updates.md
